version: '3'

services:
  #services redis
  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
      - "6379:6379"

    #interface grafica
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "4200:8081"